# Generated by Django 3.0.8 on 2021-03-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters_Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiters',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
