# Generated by Django 3.0.8 on 2021-03-02 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters_Login', '0003_auto_20210301_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=100, null=True)),
                ('salary', models.FloatField(max_length=100, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('description', models.CharField(max_length=300, null=True)),
                ('exprience', models.CharField(max_length=20, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('skills', models.CharField(max_length=60, null=True)),
                ('creationdate', models.DateField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recruiters_Login.Recruiters')),
            ],
        ),
    ]
